"""Add hotel assignment to staff

Revision ID: 141036d19e90
Revises: b5c83fc6b1f6
Create Date: 2026-09-24 23:30:26.504408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141036d19e90'
down_revision = 'b5c83fc6b1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hotels', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###
