"""Add room images

Revision ID: 27453d0260a7
Revises: 4429b01087ff
Create Date: 2026-09-13 19:06:23.083260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27453d0260a7'
down_revision = '4429b01087ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
