"""Update hotel relationship

Revision ID: 4429b01087ff
Revises: 033ea148a063
Create Date: 2026-09-13 11:08:18.769765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4429b01087ff'
down_revision = '033ea148a063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
