"""Add staff verification

Revision ID: 96f5720e70dc
Revises: 141036d19e90
Create Date: 2026-09-24 23:53:21.195595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f5720e70dc'
down_revision = '141036d19e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['staff_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
