"""Allow room numbers per hotel

Revision ID: b5c83fc6b1f6
Revises: 27453d0260a7
Create Date: 2026-09-13 20:54:44.347928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c83fc6b1f6'
down_revision = '27453d0260a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('room_number'))
        batch_op.create_unique_constraint('unique_room_per_hotel', ['hotel_id', 'room_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('unique_room_per_hotel', type_='unique')
        batch_op.create_index(batch_op.f('room_number'), ['room_number'], unique=True)

    # ### end Alembic commands ###
